table Metric1Options
	lineageTag: 0d64ce82-82bc-40c5-b7ad-8dbe67d40612

	measure Metric1Title = SELECTEDVALUE(Metric1Options[Metric])
		lineageTag: fcf09eaa-0f94-446b-8704-75f3665aed6c

	column Metric
		dataType: string
		lineageTag: 877deb31-79dc-4383-8352-1911cfc9871e
		summarizeBy: none
		sourceColumn: Metric

		extendedProperty ParameterMetadata =
				{
				  "version": 2,
				  "kind": 1,
				  "selectAllValue": "__SelectAll__"
				}

		annotation SummarizationSetBy = Automatic

	partition Metric1Options = m
		mode: import
		queryGroup: DynamicParameterInputs
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("TY7RCsMwCEX/JY9lf1SKhO0uFRKTqe1+f8V1dE96jhe885wghQWko6XlNqcdK98ryAbwCDNJF0yxnllHG8HPDZUqdtTAgqyBSqMbO3cJX7N/58ne9bWBspNrFmts9ov+i+uPs4KGwmxThDEHlKXQe8XRIUupx2H5AA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

